### ISSUE TITLE
MCP39F501 using MCP2200 

### ISSUE THREAD

**Issue by VictorTagayun** [fsteff/SmartPowerPlug#1]
Hello, Did you happen to use the demo board with MCP2200 USB to Serial?
I want to connect the Raspberry to this demo board and want to display the power.

**Comment by fsteff** [comment]
No, we created our own board and the communication took place over the RPI's GPIOs.
However, we had difficulties with the MCP39F501 - it did not measure correct values and we were not able to find the problem until the end of the project.
